"""Render conformance results as Markdown.

The output is committed to RESULTS.md, so it is written to be diffable: stable
ordering, no timestamps, no environment detail that changes between runs.
"""

from __future__ import annotations

from .corpus import CORPUS, Tier
from .runner import ToolResult

__all__ = ["render"]

_MARK = {True: "pass", False: "FAIL"}


def _is_invisible_for_display(cp: int) -> bool:
    """Whether a codepoint has to be escaped to be seen in a report.

    Deliberately wider than the cleaner's own taxonomy. A private-use
    codepoint that survives a clean renders as nothing, so printing it
    verbatim makes a real failure look like a spurious whitespace diff --
    which is exactly how one was nearly dismissed while building this.
    """
    return (
        0x200B <= cp <= 0x206F
        or 0xFE00 <= cp <= 0xFE0F
        or 0xE0000 <= cp <= 0xE007F
        or 0x180B <= cp <= 0x180E
        or 0xFFF9 <= cp <= 0xFFFB
        or 0xE000 <= cp <= 0xF8FF  # private use area
        or 0xF0000 <= cp <= 0x10FFFD  # supplementary private use
        or cp in (0x00A0, 0x00AD, 0x034F, 0x115F, 0x1160, 0x17B4, 0x17B5, 0xFEFF)
    )


def _escape(text: str) -> str:
    """Make invisible characters visible, and safe inside a table cell."""
    out: list[str] = []
    for ch in text:
        cp = ord(ch)
        if ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "|":
            out.append("\\|")
        elif cp < 0x20 or cp == 0x7F or _is_invisible_for_display(cp):
            out.append(f"U+{cp:04X}")
        else:
            out.append(ch)
    return "`" + "".join(out) + "`" if out else "``"


def render(results: list[ToolResult]) -> str:
    lines: list[str] = []
    names = [r.tool for r in results]

    lines.append("# Conformance results")
    lines.append("")
    lines.append(
        "Generated by `python -m marklens.audit`. Every row is an input with a "
        "stated expected output and a reason; see "
        "[`corpus.py`](src/marklens/audit/corpus.py)."
    )
    lines.append("")

    # --- summary ---------------------------------------------------------
    lines.append("## Summary")
    lines.append("")
    lines.append("| tool | correctness | content corrupted | contraband left in place |")
    lines.append("|---|---|---|---|")
    for r in results:
        passed, total = r.correctness
        lines.append(
            f"| {r.tool} | {passed}/{total} | {len(r.corruptions)} | {len(r.leaks)} |"
        )
    lines.append("")
    lines.append(
        "**content corrupted** counts load-bearing cases a tool damaged -- emoji "
        "sequences, subdivision flags, and Indic/Arabic orthography. **contraband "
        "left in place** counts hidden marks it failed to remove. Both are "
        "failures; the first is worse, because it silently alters the user's text."
    )
    lines.append("")

    # --- correctness detail ----------------------------------------------
    by_name = {r.tool: {o.case.name: o for o in r.outcomes} for r in results}
    for group in ("contraband", "load-bearing", "fidelity"):
        cases = [c for c in CORPUS if c.tier is Tier.CORRECTNESS and c.group == group]
        if not cases:
            continue
        lines.append(f"## Correctness: {group}")
        lines.append("")
        lines.append("| case | input | expected | " + " | ".join(names) + " |")
        lines.append("|---|---|---|" + "---|" * len(names))
        for case in cases:
            row = [case.name, _escape(case.given), _escape(case.expect)]
            for name in names:
                outcome = by_name[name].get(case.name)
                row.append("n/a" if outcome is None else _MARK[outcome.passed])
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    # --- policy detail ---------------------------------------------------
    policy = [c for c in CORPUS if c.tier is Tier.POLICY]
    if policy:
        lines.append("## Policy differences (not scored)")
        lines.append("")
        lines.append(
            "Reasonable tools disagree here. Shown so the differences are visible; "
            "scoring them would just encode one project's preferences as another's "
            "bugs."
        )
        lines.append("")
        lines.append("| case | input | " + " | ".join(names) + " |")
        lines.append("|---|---|" + "---|" * len(names))
        for case in policy:
            row = [case.name, _escape(case.given)]
            for name in names:
                outcome = by_name[name].get(case.name)
                row.append(
                    "n/a"
                    if outcome is None
                    else (outcome.error or _escape(outcome.produced))
                )
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    # --- failure rationale ----------------------------------------------
    failures = [
        (r.tool, o)
        for r in results
        for o in r.outcomes
        if o.case.tier is Tier.CORRECTNESS and not o.passed
    ]
    if failures:
        lines.append("## Why each failure matters")
        lines.append("")
        for tool, outcome in failures:
            lines.append(f"- **{tool}** / {outcome.case.name} — {outcome.case.why}.")
            if outcome.error:
                lines.append(f"  Tool error: `{outcome.error}`")
            else:
                lines.append(
                    f"  Expected {_escape(outcome.case.expect)}, "
                    f"got {_escape(outcome.produced)}."
                )
        lines.append("")

    return "\n".join(lines)
